export interface DirectoryClient {
  clientCode: string;
  erpId: string;
  nipt: string;
  clientName: string;
  projectName: string;
  address: string;
  contactPerson: string;
  email: string;
  phone: string;
}

export const officialClientCodes2026: DirectoryClient[] = [
  {
    "clientCode": "K01",
    "erpId": "K01",
    "nipt": "L41526502B",
    "clientName": "SARP & LAB Shpk",
    "projectName": "PRODHIMI DHE TREGTIMI I PRODUKTEVE KIMIKE PER NDERTIM. PUNIME LABORATORI NE TESTIMIN E MATERIALEVE TE NDERTIMIT, GJEOTEKNIKE, ETJ, KALIBRIMIN E MAKINERIVE DHE PAJISJEVE MATESE,CERTIFIKIMIN E SISTEMIT TE CILESISE, CERTIFIKIMIN E PRODUKTEVE, INSPEKTIME TE NDRYSHME, ETJ.",
    "address": "Durres, Rrashbull , Fshati Vrrin, Autostrada Tirane-Durres, km.29",
    "contactPerson": "SARP & LAB Shpk",
    "email": "d.alliu@sarpandlab.al",
    "phone": "0672022609"
  },
  {
    "clientCode": "K02",
    "erpId": "K02",
    "nipt": "",
    "clientName": "BALFIN (PALASE)",
    "projectName": "G11-G14",
    "address": "",
    "contactPerson": "BALFIN (PALASE)",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K03",
    "erpId": "K03",
    "nipt": "",
    "clientName": "DELTA CONSTRUCTION ( PALASE)",
    "projectName": "\"'DELTA FALAISE RESORT & VILLAGE'' , ZONA 1,BASHKIA HIMARE.",
    "address": "",
    "contactPerson": "DELTA CONSTRUCTION ( PALASE)",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K04",
    "erpId": "K04",
    "nipt": "",
    "clientName": "ASR INVEST",
    "projectName": "''GODINË BANIMI DHE SHËRBIMI 5-6-7 KATE ME 2 KATE DHE 3 KATE NËNTOKË, NDODHUR NË NJËSINË STRUKTURORE KZ_UB_A1_14/564'' KAMËZ, PASKUQAN",
    "address": "Rruga \"FROSINA PLAKU\" Banesa nr.7",
    "contactPerson": "ASR INVEST",
    "email": "ylli.koci.7@gmail.com",
    "phone": ""
  },
  {
    "clientCode": "K05",
    "erpId": "K05",
    "nipt": "",
    "clientName": "BREGU",
    "projectName": "BAZAAR GATE",
    "address": "Street Dervish Hima, Build Ambasador 3 Floor II, D.11, Tirana, Albania",
    "contactPerson": "BREGU",
    "email": "info@bregugroup.al",
    "phone": "+355 67 60 40 733"
  },
  {
    "clientCode": "K06",
    "erpId": "K06",
    "nipt": "",
    "clientName": "TABI CONSTRUCTION",
    "projectName": "GODINË BANIMI DHE SHËRBIMI 5, 7 KAT ME 1 KAT NËNTOKË",
    "address": "Rruga Dervish Hatixhe Pallati Mozart Kati 3, Tiranë 1001",
    "contactPerson": "TABI CONSTRUCTION",
    "email": "",
    "phone": "+355 69 707 1888"
  },
  {
    "clientCode": "K07",
    "erpId": "K07",
    "nipt": "",
    "clientName": "BALFIN (RHL)",
    "projectName": "ROLLING HILLS (LIQENI)",
    "address": "Tirane, Rruga Komuna e Parisit, Kompleksi Kika 2, Objekti 3, Kati 1",
    "contactPerson": "BALFIN (RHL)",
    "email": "www.balfinconstruction.al",
    "phone": "+355 69 203 3434"
  },
  {
    "clientCode": "K08",
    "erpId": "K08",
    "nipt": "",
    "clientName": "TEXAS DEVELOPMENT sh.p.k",
    "projectName": "OBJEKT BANIMI DHE SHERBIMESH 9 KATE MBI TOKE DHE 3 KATE PARKIM NENTOKE {\" ROSE RESIDENCE \" , Rruga Emin Duraku, Tirane}",
    "address": "Rruga e Kosovareve. Tirane, 1019",
    "contactPerson": "TEXAS DEVELOPMENT sh.p.k",
    "email": "marketing@texasdev.eu",
    "phone": "+355 694040191"
  },
  {
    "clientCode": "K09",
    "erpId": "K09",
    "nipt": "",
    "clientName": "FMD COMPANY SHPK",
    "projectName": "GODINE BANIMI DHE SHERBIMI 5, 7 ,9 DHE 11 KATE MBI TOKE ME 2 KATE PARKIM NENTOKE NE RRUGEN \"DHIMITER FRENGU\" DHE \"ANESTI LUBONJA\"",
    "address": "",
    "contactPerson": "FMD COMPANY SHPK",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K10",
    "erpId": "K10",
    "nipt": "",
    "clientName": "KLAR (ALI DEMI)",
    "projectName": "2 GODINA BANIMI DHE SHERBIMI 3.6.7 DHE 8 KATE, ME 2 KATE NENTOKE DHE 4,6,8 DHE 11 KATE, ME 2 KATE PARKIM NENTOKE NE RRUGEN \" SHYQYRI ISHMI\"",
    "address": "",
    "contactPerson": "KLAR (ALI DEMI)",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K11",
    "erpId": "K11",
    "nipt": "",
    "clientName": "PROGEEN SH.P.K",
    "projectName": "OBJEKT RESIDENCIAL AO1",
    "address": "Tirane Rruga \"Shyqyri Bërxolli\", Pallati Intercosat, Hyrja A, Kati 1",
    "contactPerson": "PROGEEN SH.P.K",
    "email": "progeen@gmail.com",
    "phone": ""
  },
  {
    "clientCode": "K12",
    "erpId": "K12",
    "nipt": "",
    "clientName": "GRAMOZI NDERTIM PROJEKTIM",
    "projectName": "GODINE BANIMI DHE SHERBIMI 5,7 DHE 9 KATE ME 2 KATE PARKIM NENTOKE",
    "address": "Yzberisht",
    "contactPerson": "GRAMOZI NDERTIM PROJEKTIM",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K13",
    "erpId": "K13",
    "nipt": "",
    "clientName": "KISHA ORTHODHOKSE AUTOQEFALE E SHQIPERISE",
    "projectName": "NDERTESE POLIFUNKSIONALE NE SHERBIM TE KISHES AUTOQEFALE ORTHODHOKSE TE SHQIPERISE , 2 ,5 DHE 10 KATE MBI TOKE ME 1 KAT NENTOKE NE RRUGEN E \"KAVAJES\"",
    "address": "Rruga e Kavajës, Tiranë",
    "contactPerson": "KISHA ORTHODHOKSE AUTOQEFALE E SHQIPERISE",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K14",
    "erpId": "K14",
    "nipt": "",
    "clientName": "DUKAGJINI SHPK",
    "projectName": "DUKAGJINI RESORT",
    "address": "Tirane, Njesia Administrative Nr.2. Rruga e Elbasanit, Zona Kadastrale 8160, Pasuria Nr.5/181,",
    "contactPerson": "DUKAGJINI SHPK",
    "email": "korab.lluka@dukagjinigroup.com",
    "phone": ""
  },
  {
    "clientCode": "K15",
    "erpId": "K15",
    "nipt": "",
    "clientName": "VEZI GROUP",
    "projectName": "LION RESIDENCE 2",
    "address": "Rruga ish. SMT, Banesë me nr. 021, Zona kadastrale 3255, Sallmone, Xhafzotaj, Durrës",
    "contactPerson": "VEZI GROUP",
    "email": "",
    "phone": "+355673514784"
  },
  {
    "clientCode": "K16",
    "erpId": "K16",
    "nipt": "",
    "clientName": "SUKAJ CONSTRUCTION",
    "projectName": "OBJEKT BANIMI 4 KATE DHE 6 KATE + 1 KAT NËNTOKË NË RRUGËN \"ABDYL PAJO\" NË NJËSINË TR/310",
    "address": "Tiranë , Rruga \"JORGO PLAKU\" Nr 1",
    "contactPerson": "SUKAJ CONSTRUCTION",
    "email": "sukaj@live.com",
    "phone": "+355 69 206 6757"
  },
  {
    "clientCode": "K17",
    "erpId": "K17",
    "nipt": "",
    "clientName": "AB GRAMOZI (PALLATI)",
    "projectName": "GODINE BANIMI DHE SHERBIMESH 1, 4 DHE 6 KAT, ME 3 KAT PARKIM NENTOKE",
    "address": "Tiranë Njësia Nr. 2, Rruga Themistokli Germenji, Pallati Frasheri, Shkalla 1, Apartamenti 16",
    "contactPerson": "AB GRAMOZI (PALLATI)",
    "email": "",
    "phone": "+355672044407"
  },
  {
    "clientCode": "K18",
    "erpId": "K18",
    "nipt": "",
    "clientName": "SIBA",
    "projectName": "B-06 , TIRANA BUSINESS PARK",
    "address": "Rinas",
    "contactPerson": "SIBA",
    "email": "info@siba.al",
    "phone": ""
  },
  {
    "clientCode": "K19",
    "erpId": "K19",
    "nipt": "M32009501K",
    "clientName": "ARMOND BRIJA",
    "projectName": "SHTRIM SHESHI",
    "address": "Shenavlash, Pallate e reja",
    "contactPerson": "ARMOND BRIJA",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K20",
    "erpId": "K20",
    "nipt": "",
    "clientName": "EUROBETON 2005",
    "projectName": "IMPIANT PRODHIMI BETONI",
    "address": "",
    "contactPerson": "EUROBETON 2005",
    "email": "'eurobeton2005shpk@gmail.com",
    "phone": ""
  },
  {
    "clientCode": "K21",
    "erpId": "K21",
    "nipt": "",
    "clientName": "BALFIN (VLORA MARINE)",
    "projectName": "VLORA MARINE RESORT, HOTEL DHE STRUKTURA AKOMODUESE REZIDENCIALE , VLORE",
    "address": "Komuna e Parisit, Rezidenca Kika 2, Tiranë, Shqipëria",
    "contactPerson": "BALFIN (VLORA MARINE)",
    "email": "info@manetci.al",
    "phone": "Mob.: +355 69 808 1313"
  },
  {
    "clientCode": "K22",
    "erpId": "K22",
    "nipt": "",
    "clientName": "FUNDWAY L.L.C",
    "projectName": "'STRUKTURE AKOMODUESE REZIDENCIALE DHE MARINA RESORT,BLLOKU 5, OBJEKTI B2 ''",
    "address": "Porti,Vlore",
    "contactPerson": "FUNDWAY L.L.C",
    "email": "",
    "phone": "Mob :+383 48 180 018"
  },
  {
    "clientCode": "K23",
    "erpId": "K23",
    "nipt": "",
    "clientName": "KOTARJA NDERTIM",
    "projectName": "GODINE BANIMI DHE SHERBIMESH 1 , 5 , 7 DHE 9 KATE ME 1 KAT NENTOKE NE RRUGEN \"PEKINI\" BASHKIA KAMEZ",
    "address": "Tirane Kamez Rr.Teuta,prane shkolles 9-vjecare \"100-Vjetori\" , Nr pasurie 129/812,zona kadastrale 2066,Kamez,Tirane 1030",
    "contactPerson": "KOTARJA NDERTIM",
    "email": "fatoskotarja@hotmail.com",
    "phone": "+355686419382"
  },
  {
    "clientCode": "K24",
    "erpId": "K24",
    "nipt": "",
    "clientName": "BALFIN 2",
    "projectName": "ROLLING HILLS 2",
    "address": "",
    "contactPerson": "BALFIN 2",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K25",
    "erpId": "K25",
    "nipt": "",
    "clientName": "ARELA KONSTRUKSION 2019",
    "projectName": "?",
    "address": "",
    "contactPerson": "ARELA KONSTRUKSION 2019",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K26",
    "erpId": "K26",
    "nipt": "",
    "clientName": "DESLA",
    "projectName": "STRUKTURE HOTELERIE 8 KATE DHE 1 KAT NENTOKE",
    "address": "Durres Rruga Skenderbe, Lagjja nr.11, Bulevardi",
    "contactPerson": "DESLA",
    "email": "",
    "phone": "+355 69 204 9190"
  },
  {
    "clientCode": "K27",
    "erpId": "K27",
    "nipt": "",
    "clientName": "OPTIMUM PROPERTY",
    "projectName": "ADRIA RESIDENCE",
    "address": "Tiranë, Golem, Karpen-Kavajë, Zona Kadastrale nr 2099, Pasuria nr 92/63",
    "contactPerson": "OPTIMUM PROPERTY",
    "email": "info@brillant.al",
    "phone": ""
  },
  {
    "clientCode": "K28",
    "erpId": "K28",
    "nipt": "",
    "clientName": "CLAUDIO SHPK",
    "projectName": "STRUKTURA BANIMI DHE APART-HOTEL 5 KAT + 1 KAT NËNTOKË + KABINË ELEKTIKE",
    "address": "Fshati Golem , Nj.Adm. Golem, Bashkia Kavaje",
    "contactPerson": "CLAUDIO SHPK",
    "email": "Claudio-shpk@hotmail.com",
    "phone": ""
  },
  {
    "clientCode": "K29",
    "erpId": "K29",
    "nipt": "",
    "clientName": "GRIBA",
    "projectName": "DURRES YACHT MARINA , PLOT 2B04",
    "address": "Rruga Don Bosko, Tiranë, Shqipëri",
    "contactPerson": "GRIBA",
    "email": "info@griba-shpk.com",
    "phone": "+355 69 207 8467"
  },
  {
    "clientCode": "K30",
    "erpId": "K30",
    "nipt": "",
    "clientName": "HANXHARI",
    "projectName": "IMPJANT PRODHIMI BETONI",
    "address": "Vlore",
    "contactPerson": "HANXHARI",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K31",
    "erpId": "K31",
    "nipt": "",
    "clientName": "BOLV OIL SHPK (PALASE)",
    "projectName": "'GREEN COAST RESORT 2,ZONA JA,OBJEKTBANIMI DHE SHERBIME 1,2,3,4 DHE 5 KATE MBI TOKE ME 1 KAT NENTOKE DHE VILA INDIVIDUALE ME 2 KATE MBI TOKE ME MUR RRETHUES DHE HAPSIRA REKREATIVE ME PISHINE ''",
    "address": "Rr. 7 Nëntori, Fushë Mëzez, Komuna Kashar, Tiranë, Shqipëri",
    "contactPerson": "BOLV OIL SHPK (PALASE)",
    "email": "info@bolv.al",
    "phone": "+355 69 70 07 000"
  },
  {
    "clientCode": "K32",
    "erpId": "K32",
    "nipt": "",
    "clientName": "XHULIO",
    "projectName": "IMPJANT PRODHIMI INERTESH",
    "address": "Himare",
    "contactPerson": "XHULIO",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K33",
    "erpId": "K33",
    "nipt": "",
    "clientName": "TABI CONSTRUCTION",
    "projectName": "IMPJANT PRODHIMI INERTESH",
    "address": "Rruga Dervish Hatixhe Pallati Mozart Kati 3, Tiranë 1001",
    "contactPerson": "TABI CONSTRUCTION",
    "email": "",
    "phone": "+355 69 707 1888"
  },
  {
    "clientCode": "K34",
    "erpId": "K34",
    "nipt": "",
    "clientName": "ALBA BETON",
    "projectName": "IMPJANT PRODHIM BETONI",
    "address": "",
    "contactPerson": "ALBA BETON",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K35",
    "erpId": "K35",
    "nipt": "",
    "clientName": "KLAR (PASKUQAN)",
    "projectName": "OBJEKT SHERBIMI DHE BANIMI 6,7,8 DHE 9 KATE ME 2 KATE PARKIMI NENTOKE NE RRUGEN \"DEMOKRACIA\" , PASKUQAN , KAMEZ",
    "address": "Tiranë, \"Rruga Dervish Hatixhe, Pallati Mozart, Kati i 2, Zip Code 1001\"",
    "contactPerson": "KLAR (PASKUQAN)",
    "email": "",
    "phone": "lim-em@lim-em.al"
  },
  {
    "clientCode": "K36",
    "erpId": "K36",
    "nipt": "MALI ROBIT",
    "clientName": "GRAMOZI NDERTIM PROJEKTIM",
    "projectName": "GODINE BANIMI DHE SHERBIME 2 , 3 , 4 , 5 KATE ME 1 KAT NENTOKE",
    "address": "Tiranë Njësia Nr. 2, Rruga Themistokli Germenji, Pallati Frasheri, Shkalla 1, Apartamenti 16",
    "contactPerson": "GRAMOZI NDERTIM PROJEKTIM",
    "email": "",
    "phone": "+355672044407"
  },
  {
    "clientCode": "K37",
    "erpId": "K37",
    "nipt": "",
    "clientName": "FERRO BETON",
    "projectName": "IMPJANT PRODHIM BETONI",
    "address": "",
    "contactPerson": "FERRO BETON",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K38",
    "erpId": "K38",
    "nipt": "",
    "clientName": "BREGU",
    "projectName": "G16",
    "address": "",
    "contactPerson": "BREGU",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K39",
    "erpId": "K39",
    "nipt": "",
    "clientName": "LLAZO",
    "projectName": "GREENNAT BALLSH",
    "address": "Kolonjë, Bishqethem, Bishqethem 1, Rruga Këmishtaj, zona kadastrale 1197, nr pasurie 3/21",
    "contactPerson": "LLAZO",
    "email": "",
    "phone": "+35567 20 60 901"
  },
  {
    "clientCode": "K40",
    "erpId": "K40",
    "nipt": "",
    "clientName": "LLAZO",
    "projectName": "IMPJANT PRODHIM BETONI",
    "address": "Kolonjë, Bishqethem, Bishqethem 1, Rruga Këmishtaj, zona kadastrale 1197, nr pasurie 3/21",
    "contactPerson": "LLAZO",
    "email": "",
    "phone": "+35567 20 60 901"
  },
  {
    "clientCode": "K41",
    "erpId": "K41",
    "nipt": "",
    "clientName": "ROKLI KONSTRUKSION",
    "projectName": "GODINË BANIMI DHE SHËRBIMESH 8,9 DHE 10 KATE ME 2 KATE PARKIM NËNTOKË, NË RRUGËN '' ALI PASHË GUCIA''",
    "address": "",
    "contactPerson": "ROKLI KONSTRUKSION",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K42",
    "erpId": "K42",
    "nipt": "",
    "clientName": "XHIAR 2009",
    "projectName": "",
    "address": "",
    "contactPerson": "XHIAR 2009",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K43",
    "erpId": "K43",
    "nipt": "",
    "clientName": "ALB LAB",
    "projectName": "",
    "address": "",
    "contactPerson": "ALB LAB",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K44",
    "erpId": "K44",
    "nipt": "",
    "clientName": "E&E NDERTIM",
    "projectName": "IMPIANT PRODHIMI BETONI",
    "address": "Durrës, Spitallë, pasuria nr.69/13, zona kadastrale 8517vol.4, faqe 40",
    "contactPerson": "E&E NDERTIM",
    "email": "",
    "phone": "+355682039744"
  },
  {
    "clientCode": "K45",
    "erpId": "K45",
    "nipt": "",
    "clientName": "ALESIO 2014",
    "projectName": "IMPIANT PRODHIMI BETONI",
    "address": "VORE",
    "contactPerson": "ALESIO 2014",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K46",
    "erpId": "K46",
    "nipt": "",
    "clientName": "PROGEEN",
    "projectName": "UNIVERS CITY, QTU",
    "address": "Tirane Rruga \"Shyqyri Bërxolli\", Pallati Intercosat, Hyrja A, Kati 1",
    "contactPerson": "PROGEEN",
    "email": "",
    "phone": "Email: progeen@gmail.com"
  },
  {
    "clientCode": "K47",
    "erpId": "K47",
    "nipt": "",
    "clientName": "ASTRA 2014 SHPK",
    "projectName": "GODINE 5 , 7 DHE 9 KATE + 2 KATE PODRUM ME DESTINACION BANIM",
    "address": "Paskuqan , Tirane",
    "contactPerson": "ASTRA 2014 SHPK",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K48",
    "erpId": "K48",
    "nipt": "",
    "clientName": "BLATON",
    "projectName": "FABRIKE PRODHIMI INERTESH",
    "address": "",
    "contactPerson": "BLATON",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K49",
    "erpId": "K49",
    "nipt": "",
    "clientName": "?",
    "projectName": "Wild hotel",
    "address": "",
    "contactPerson": "?",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K50",
    "erpId": "K50",
    "nipt": "",
    "clientName": "EUROCOL",
    "projectName": "'KOMPLEKS BANIMI ME 19 STRUKTURA 1 DHE 4 KT, ME 1 DHE 2 KT PARKIM NËNTOKË, OBJEKT 1 KAT SHËRBIM, ME MUR RRETHUES, NË RRUGËN ''HIQMET BUZI' SAUK , TIRANË",
    "address": "Murat Toptani, qendër biznesi Euroco11, Tiranë",
    "contactPerson": "EUROCOL",
    "email": "eurocol@eurocol.com.al",
    "phone": ""
  },
  {
    "clientCode": "K51",
    "erpId": "K51",
    "nipt": "",
    "clientName": "SKENDER MUÇO",
    "projectName": "IIMPJANT PRODHIM INERTESH",
    "address": "Sarande",
    "contactPerson": "SKENDER MUÇO",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K52",
    "erpId": "K52",
    "nipt": "",
    "clientName": "ARDI 2M",
    "projectName": "SHTEPI BANIMI 2 KAT+PODRUM, BUJAR ZEQIRI",
    "address": "-",
    "contactPerson": "ARDI 2M",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K53",
    "erpId": "K53",
    "nipt": "",
    "clientName": "(MURATI GROUP) XH&M",
    "projectName": "HOTELERI , GJIRI I LALZIT",
    "address": "",
    "contactPerson": "(MURATI GROUP) XH&M",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K54",
    "erpId": "K54",
    "nipt": "",
    "clientName": "(ALFA BETON) BEGA 07",
    "projectName": "IMPIANT PRODHIMI BETONI",
    "address": "HIMARE",
    "contactPerson": "(ALFA BETON) BEGA 07",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K55",
    "erpId": "K55",
    "nipt": "",
    "clientName": "FENIKS CONSTRUCTION",
    "projectName": "IMPIANT PRODHIMI INERTESH",
    "address": "",
    "contactPerson": "FENIKS CONSTRUCTION",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K56",
    "erpId": "K56",
    "nipt": "",
    "clientName": "KLAJDI NDERTIM",
    "projectName": "GODINA BANIMI SHUMEKATESHE",
    "address": "",
    "contactPerson": "KLAJDI NDERTIM",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K57",
    "erpId": "K57",
    "nipt": "",
    "clientName": "ARKON STUDIO",
    "projectName": "KOMPANI PROJEKTIMI DHE NDERTIMI",
    "address": "VLORE",
    "contactPerson": "ARKON STUDIO",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K58",
    "erpId": "K58",
    "nipt": "",
    "clientName": "RAFAELO",
    "projectName": "IMPJANT PRODHIM BETONI",
    "address": "VORE",
    "contactPerson": "RAFAELO",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K59",
    "erpId": "K59",
    "nipt": "M31313501O",
    "clientName": "HFE CONSTRUCTION",
    "projectName": "RESIDENCE & SOLEI",
    "address": "",
    "contactPerson": "HFE CONSTRUCTION",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K60",
    "erpId": "K60",
    "nipt": "",
    "clientName": "LLAZO",
    "projectName": "MORINA CITY 5-6 KATE MBI TOKE - 2 KATE NENTOKE",
    "address": "",
    "contactPerson": "LLAZO",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K61",
    "erpId": "K61",
    "nipt": "",
    "clientName": "RAFAELO",
    "projectName": "IMPJANT PRODHIM BETONI",
    "address": "SHENKOLL",
    "contactPerson": "RAFAELO",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K62",
    "erpId": "K62",
    "nipt": "",
    "clientName": "PEPA GROUP",
    "projectName": "IMPIANT PRODHIMI BETONI",
    "address": "Autostrada Tirane Durres km 6, Zona Kadastrale nr.2105, Nr Pasurie 1168/13, Kashar, Tirane",
    "contactPerson": "PEPA GROUP",
    "email": "",
    "phone": "+3555698002020"
  },
  {
    "clientCode": "K63",
    "erpId": "K63",
    "nipt": "",
    "clientName": "AB GRAMOZI (VILAT)",
    "projectName": "KOMPLEKS ME VILA BANIMI 1 DHE 2 KAT, OBJEKT SHERBIMI 1 KAT, KABINE ROJE DHE KABINE ELEKTRIKE 1 KAT SI DHE MUR RRETHUES",
    "address": "Tiranë Njësia Nr. 2, Rruga Themistokli Germenji, Pallati Frasheri, Shkalla 1, Apartamenti 16",
    "contactPerson": "AB GRAMOZI (VILAT)",
    "email": "",
    "phone": "+355672044407"
  },
  {
    "clientCode": "K64",
    "erpId": "K64",
    "nipt": "",
    "clientName": "GENTIAN BYTYCI (PAJA)",
    "projectName": "PRISHJE E OBJEKTIT EKZISTUES DHE NDERTIMI I OBJEKTIT TE BANIMIT 1 KAT +PISHINE +1 KAT NENTOKE",
    "address": "Rruga ''17 Janari'' Durres",
    "contactPerson": "GENTIAN BYTYCI (PAJA)",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K65",
    "erpId": "K65",
    "nipt": "",
    "clientName": "TABI CONSTRUCTION",
    "projectName": "ARDEN HILL",
    "address": "",
    "contactPerson": "TABI CONSTRUCTION",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K66",
    "erpId": "K66",
    "nipt": "",
    "clientName": "GENTRY-AL CONSTRUCTION SH.P.K",
    "projectName": "STRUKTURE BANIMI DHE ME APARTAMENTE AKOMODUESE ME 5 DHE 7 KATE MBI TOKE DHE ME 2 KATE PARKIM NENTOKE , ME NJESINE STRUKTURORE G1-A41-08, BASHKIA KAVAJE",
    "address": "GOLEM",
    "contactPerson": "GENTRY-AL CONSTRUCTION SH.P.K",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K67",
    "erpId": "K67",
    "nipt": "",
    "clientName": "ALB CONSULTING 2",
    "projectName": "LABORATOR NDERTIMI",
    "address": "TIRANE",
    "contactPerson": "ALB CONSULTING 2",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K68",
    "erpId": "K68",
    "nipt": "",
    "clientName": "KONTAKT KADIU",
    "projectName": "",
    "address": "",
    "contactPerson": "KONTAKT KADIU",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K69",
    "erpId": "K69",
    "nipt": "",
    "clientName": "PRIME BLOCK SHPK",
    "projectName": "PRODHUES",
    "address": "",
    "contactPerson": "PRIME BLOCK SHPK",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K70",
    "erpId": "K70",
    "nipt": "",
    "clientName": "GIMI",
    "projectName": "FIER",
    "address": "",
    "contactPerson": "GIMI",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K71",
    "erpId": "K71",
    "nipt": "",
    "clientName": "BOE: '' NG STRUCTURES shpk & GPG COMPANY shpk''",
    "projectName": "NDERTIM SHKOLLA 9 VJECARE TIPI 2 DHE E MESME TIPI 4, NJESIA STRUKTURORE RRUGA ''3 DESHMORET''",
    "address": "",
    "contactPerson": "BOE: '' NG STRUCTURES shpk & GPG COMPANY shpk''",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K72",
    "erpId": "K72",
    "nipt": "",
    "clientName": "SHEHU 2 & VELLEZERIT TAFA shpk''",
    "projectName": "GODINE BANIMI 5&6 kate, 1 kat Nentoke, Golem, Kavaje",
    "address": "",
    "contactPerson": "SHEHU 2 & VELLEZERIT TAFA shpk''",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K73",
    "erpId": "K73",
    "nipt": "",
    "clientName": "ALFED shpk''",
    "projectName": "OBJEKT BANIMI 6 KATE , ME 1 KAT PARKIM NENTOKE , GOLEM",
    "address": "",
    "contactPerson": "ALFED shpk''",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K74",
    "erpId": "K74",
    "nipt": "",
    "clientName": "DYRRAKIUM CONSTRUCTION",
    "projectName": "KOMPLEKS POLIFUNKSIONAL TURISTIK , DURRES",
    "address": "Durrës, Lagjja 8, Rruga\" Hajdar Demiri\", Zona Kadastrale 8512, Godinë 1-Katëshe, Nr. pasurise 8/1",
    "contactPerson": "DYRRAKIUM CONSTRUCTION",
    "email": "bledarkertusha1985@gmail.com",
    "phone": ""
  },
  {
    "clientCode": "K75",
    "erpId": "K75",
    "nipt": "",
    "clientName": "ERALD SHALA",
    "projectName": "?",
    "address": "Rrashbull, Durres",
    "contactPerson": "ERALD SHALA",
    "email": "",
    "phone": "Tel.:069 35 39 993"
  },
  {
    "clientCode": "K76",
    "erpId": "K76",
    "nipt": "M53429802O",
    "clientName": "URBAN X",
    "projectName": "URBAN RESIDENCE",
    "address": "",
    "contactPerson": "URBAN X",
    "email": "",
    "phone": "Tel.:069 78 08 555"
  },
  {
    "clientCode": "K77",
    "erpId": "K77",
    "nipt": "",
    "clientName": "WALTER CONSTRUCTION",
    "projectName": "GODINE BANIMI 2 KATE",
    "address": "",
    "contactPerson": "WALTER CONSTRUCTION",
    "email": "",
    "phone": "Tel.:067 49 99 386"
  },
  {
    "clientCode": "K78",
    "erpId": "K78",
    "nipt": "",
    "clientName": "GB CIVIL ENGINEERIG",
    "projectName": "GODINE BANIMI 3 KATE PLUS 1 KAT PODRUM",
    "address": "Maminas",
    "contactPerson": "GB CIVIL ENGINEERIG",
    "email": "",
    "phone": "Tel.:067 77 01 032"
  },
  {
    "clientCode": "K79",
    "erpId": "K79",
    "nipt": "",
    "clientName": "DIONIS KOLA",
    "projectName": "STRUKTURE BANIMI 2 KATE DHE 1 KAT NENTOKE , PANELE FOLTOVOLTAIKE , PISHINE DHE MUR RRETHUES",
    "address": "SPITALL , DURRES",
    "contactPerson": "DIONIS KOLA",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K80",
    "erpId": "K80",
    "nipt": "",
    "clientName": "PAJTONI RH",
    "projectName": "KOMPLEKS ME VILA BANIMI 1, 2 DHE 3 KAT ME 1 KAT PJESËRISHT NËNTOKË, ME PISHINA, DEPO UJI, KABINË ELEKTRIKE 1 KAT DHE ME MUR RRETHUES, NË PRONË TË Z.SAMIR MANE",
    "address": "Tiranë, Kashar, Mezez, Autostrada Tr-Dr, Km 5, Godina DELTA SHA.",
    "contactPerson": "PAJTONI RH",
    "email": "info@pajtoni.al",
    "phone": "+355684089920"
  },
  {
    "clientCode": "K81",
    "erpId": "K81",
    "nipt": "",
    "clientName": "VOKRRI INVEST (ERDIAR RESIDENCE)",
    "projectName": "APART HOTEL 6 KATE DHE 1 KAT NENTOKE",
    "address": "QERRET GOLEM",
    "contactPerson": "VOKRRI INVEST (ERDIAR RESIDENCE)",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K82",
    "erpId": "K82",
    "nipt": "",
    "clientName": "TIDO BETON",
    "projectName": "",
    "address": "VALIAS ,TIRANE",
    "contactPerson": "TIDO BETON",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K83",
    "erpId": "K83",
    "nipt": "",
    "clientName": "KLAR (PASKUQAN 2)",
    "projectName": "GODINE BANIMI DHE SHERBIMESH 2 , 4 , 5 DHE 6 KATE ME 3 KATE PARKIM NENTOKE",
    "address": "",
    "contactPerson": "KLAR (PASKUQAN 2)",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K84",
    "erpId": "K84",
    "nipt": "",
    "clientName": "DURRES MARINA (ARBRI CONSTRUCTION)",
    "projectName": "2A03",
    "address": "",
    "contactPerson": "DURRES MARINA (ARBRI CONSTRUCTION)",
    "email": "e",
    "phone": ""
  },
  {
    "clientCode": "K85",
    "erpId": "K85",
    "nipt": "",
    "clientName": "EBG",
    "projectName": "",
    "address": "",
    "contactPerson": "EBG",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K86",
    "erpId": "K86",
    "nipt": "",
    "clientName": "KOTARJA NDERTIM",
    "projectName": "GODINE BANIMI 4,5 DHE 6 KATE NE RRUGEN ALTRUIST",
    "address": "",
    "contactPerson": "KOTARJA NDERTIM",
    "email": "",
    "phone": ""
  },
  {
    "clientCode": "K87",
    "erpId": "K87",
    "nipt": "",
    "clientName": "AL-ASFALT",
    "projectName": "IMPIANT PRODHIM ASFALTI",
    "address": "",
    "contactPerson": "AL-ASFALT",
    "email": "",
    "phone": ""
  }
];

export const futureErpClients = officialClientCodes2026;
