export interface DirectoryClient {
  erpId: string;
  nipt: string;
  clientName: string;
  contactPerson: string;
  email: string;
  phone: string;
}

export const futureErpClients: DirectoryClient[] = [
  { erpId: "1469", nipt: "J61918031C", clientName: "ANDI KONSTRUKSION SHPK", contactPerson: "ANDI KONSTRUKSION SHPK", email: "", phone: "" },
  { erpId: "1468", nipt: "", clientName: "Armond Fasliu", contactPerson: "Armond Fasliu", email: "", phone: "" },
  { erpId: "1467", nipt: "NOA HOLDING", clientName: "NOA HOLDING", contactPerson: "NOA HOLDING", email: "", phone: "" },
  { erpId: "1466", nipt: "", clientName: "Esjan Hysa", contactPerson: "Esjan Hysa", email: "", phone: "" },
  { erpId: "1465", nipt: "", clientName: "Suljan Elezi", contactPerson: "Suljan Elezi", email: "", phone: "" },
  { erpId: "1464", nipt: "", clientName: "Avdyl Lacko", contactPerson: "Avdyl Lacko", email: "", phone: "" },
  { erpId: "1463", nipt: "", clientName: "Fatmir Meco", contactPerson: "Fatmir Meco", email: "", phone: "" },
  { erpId: "1462", nipt: "", clientName: "Alket Stroka", contactPerson: "Alket Stroka", email: "", phone: "" },
  { erpId: "1461", nipt: "K74401601R", clientName: "Dege e shoqerise se huaj STRABAG AG", contactPerson: "Dege e shoqerise se huaj STRABAG AG", email: "afife.lapardhaja@strabag.com", phone: "0694078544" },
  { erpId: "1460", nipt: "L12121026C", clientName: "EBG GROUP", contactPerson: "EBG GROUP", email: "a.bani@ebg.al", phone: "0693913362" },
  { erpId: "1459", nipt: "", clientName: "Bardhyl Reka", contactPerson: "Bardhyl Reka", email: "", phone: "" },
  { erpId: "1458", nipt: "", clientName: "Fatmir Drasa", contactPerson: "Fatmir Drasa", email: "", phone: "" },
  { erpId: "1457", nipt: "G60303203D", clientName: "Afrim Pacolli", contactPerson: "Afrim Pacolli", email: "", phone: "" },
  { erpId: "1456", nipt: "L46727004I", clientName: "Blerime Zagani", contactPerson: "Blerime Zagani", email: "", phone: "" },
  { erpId: "1455", nipt: "", clientName: "Ervin Arapi", contactPerson: "Ervin Arapi", email: "", phone: "" },
  { erpId: "1454", nipt: "", clientName: "Martin Jahu", contactPerson: "Martin Jahu", email: "", phone: "" },
  { erpId: "1453", nipt: "", clientName: "Altin Xhaferri", contactPerson: "Altin Xhaferri", email: "", phone: "" },
  { erpId: "1452", nipt: "", clientName: "Lulzim Alla", contactPerson: "Lulzim Alla", email: "", phone: "" },
  { erpId: "1451", nipt: "", clientName: "Ervis Dedolli", contactPerson: "Ervis Dedolli", email: "", phone: "" },
  { erpId: "1450", nipt: "", clientName: "Sherit Duka", contactPerson: "Sherit Duka", email: "", phone: "" },
  { erpId: "1449", nipt: "", clientName: "Andi Kleci", contactPerson: "Andi Kleci", email: "", phone: "" },
  { erpId: "1447", nipt: "M31710016F", clientName: "Commercial Contact dega ne Shqiperi", contactPerson: "Commercial Contact dega ne Shqiperi", email: "", phone: "" },
  { erpId: "1446", nipt: "J40910052D", clientName: "Dionis Kola", contactPerson: "Dionis Kola", email: "", phone: "" },
  { erpId: "1445", nipt: "", clientName: "Endri Lika", contactPerson: "Endri Lika", email: "", phone: "" },
  { erpId: "1444", nipt: "", clientName: "Marsel Velaj", contactPerson: "Marsel Velaj", email: "", phone: "" },
  { erpId: "1443", nipt: "", clientName: "Arber Neza", contactPerson: "Arber Neza", email: "", phone: "" },
  { erpId: "1442", nipt: "", clientName: "Arben Isaku", contactPerson: "Arben Isaku", email: "", phone: "" },
  { erpId: "1440", nipt: "L71820501V", clientName: "Gëzim Ademi", contactPerson: "Gëzim Ademi", email: "", phone: "" },
  { erpId: "1439", nipt: "M08029302A", clientName: "DU & ER", contactPerson: "DU & ER", email: "", phone: "" },
  { erpId: "1438", nipt: "", clientName: "Arjan Lita", contactPerson: "Arjan Lita", email: "", phone: "" },
  { erpId: "1437", nipt: "", clientName: "Gjin Isufi", contactPerson: "Gjin Isufi", email: "", phone: "" },
  { erpId: "1436", nipt: "", clientName: "GREG SHPK", contactPerson: "GREG SHPK", email: "", phone: "M44823803F" },
  { erpId: "1434", nipt: "L51825011V", clientName: "G B Civil Engineering", contactPerson: "G B Civil Engineering", email: "gbcivilengineering@outlook.com", phone: "0692052257" },
  { erpId: "1432", nipt: "K31527598A", clientName: "REOM", contactPerson: "REOM", email: "", phone: "" },
  { erpId: "1431", nipt: "", clientName: "Xhovani Arinaj", contactPerson: "Xhovani Arinaj", email: "", phone: "" },
  { erpId: "1429", nipt: "", clientName: "Sali Saliasi", contactPerson: "Sali Saliasi", email: "", phone: "" },
  { erpId: "1428", nipt: "", clientName: "Erjon Kastrati", contactPerson: "Erjon Kastrati", email: "", phone: "" },
  { erpId: "1426", nipt: "", clientName: "Vini Ezeli", contactPerson: "Vini Ezeli", email: "", phone: "" },
  { erpId: "1424", nipt: "M52912801D", clientName: "DENI COMPANY", contactPerson: "DENI COMPANY", email: "", phone: "" },
  { erpId: "1423", nipt: "", clientName: "Elton Kaci", contactPerson: "Elton Kaci", email: "", phone: "" },
  { erpId: "1422", nipt: "K72522811C", clientName: "ALFED\" SHPK", contactPerson: "ALFED SHPK", email: "lemimucaj@gmail.com", phone: "0692050040" },
  { erpId: "1421", nipt: "", clientName: "Agim Cejku", contactPerson: "Agim Cejku", email: "", phone: "" },
  { erpId: "1420", nipt: "", clientName: "Flavi Ferhati", contactPerson: "Flavi Ferhati", email: "", phone: "" },
  { erpId: "1417", nipt: "", clientName: "Merita Semi", contactPerson: "Merita Semi", email: "", phone: "" },
  { erpId: "1416", nipt: "", clientName: "Olti Prifti", contactPerson: "Olti Prifti", email: "", phone: "" },
  { erpId: "1415", nipt: "", clientName: "Eni", contactPerson: "Eni", email: "", phone: "" },
  { erpId: "1414", nipt: "J61824069W", clientName: "ANORIA", contactPerson: "ANORIA", email: "anoria@anoria.al", phone: "0682038602" },
  { erpId: "1413", nipt: "", clientName: "Altin Hysenbelli", contactPerson: "Altin Hysenbelli", email: "", phone: "" },
  { erpId: "1412", nipt: "M32428022R", clientName: "SELECT GROUP", contactPerson: "SELECT GROUP", email: "qefalia.rigers@yahoo.com", phone: "0697483084" },
  { erpId: "1411", nipt: "K62505801B", clientName: "HABILI shpk", contactPerson: "HABILI shpk", email: "habilishpk@hotmail.com", phone: "0682021538" },
  { erpId: "1410", nipt: "", clientName: "Ram Shabani", contactPerson: "Ram Shabani", email: "", phone: "" },
  { erpId: "1409", nipt: "", clientName: "Isa", contactPerson: "Isa", email: "", phone: "" },
  { erpId: "1408", nipt: "M43323801S", clientName: "Ezan Construction 2024", contactPerson: "Ezan Construction 2024", email: "", phone: "" },
  { erpId: "1407", nipt: "", clientName: "Ervin Sula", contactPerson: "Ervin Sula", email: "", phone: "" },
  { erpId: "1406", nipt: "", clientName: "Agim Karina", contactPerson: "Agim Karina", email: "", phone: "" },
  { erpId: "1405", nipt: "", clientName: "Gezim Zaimi", contactPerson: "Gezim Zaimi", email: "", phone: "" },
  { erpId: "1404", nipt: "", clientName: "Nokja Lata", contactPerson: "Nokja Lata", email: "", phone: "" },
  { erpId: "1403", nipt: "", clientName: "Izmir Breshni", contactPerson: "Izmir Breshni", email: "", phone: "" },
  { erpId: "1402", nipt: "", clientName: "Zaim Muca", contactPerson: "Zaim Muca", email: "", phone: "" },
  { erpId: "1401", nipt: "", clientName: "Mehmet Cakoni", contactPerson: "Mehmet Cakoni", email: "", phone: "" },
  { erpId: "1400", nipt: "", clientName: "Albjon Salla", contactPerson: "Albjon Salla", email: "", phone: "" },
  { erpId: "1399", nipt: "K96706002G", clientName: "VETAL", contactPerson: "VETAL", email: "a.loloci@vetal.al", phone: "0688048546" },
  { erpId: "1398", nipt: "", clientName: "Ndricim Sela", contactPerson: "Ndricim Sela", email: "", phone: "" },
  { erpId: "1397", nipt: "L91625034L", clientName: "Walter Construction", contactPerson: "Walter Construction", email: "studiovalteri2019@gmail.com", phone: "0699495911" },
  { erpId: "1396", nipt: "", clientName: "Rafaelo 2019", contactPerson: "Rafaelo 2019", email: "", phone: "" },
  { erpId: "1395", nipt: "", clientName: "Mohammed Shawqi", contactPerson: "Mohammed Shawqi", email: "", phone: "" },
  { erpId: "1394", nipt: "L21318030U", clientName: "MW Plan shpk", contactPerson: "MW Plan", email: "mitro@mwgmbh.com", phone: "0696043537" },
  { erpId: "1393", nipt: "L57422001A", clientName: "Edil Project", contactPerson: "Edil Project", email: "pjeroscutari@yahoo.com", phone: "0692020608" },
  { erpId: "1392", nipt: "", clientName: "Ramiz Nika", contactPerson: "Ramiz Nika", email: "", phone: "" },
  { erpId: "1391", nipt: "", clientName: "Lulzim Luli", contactPerson: "Lulzim Luli", email: "", phone: "" },
  { erpId: "1389", nipt: "M34720801Q", clientName: "RIVIERA INVESTMENT", contactPerson: "RIVIERA INVESTMENT", email: "progonatishpk@gmail.com", phone: "0692094036" },
  { erpId: "1388", nipt: "", clientName: "Silda Boka", contactPerson: "Silda Boka", email: "", phone: "" },
  { erpId: "1387", nipt: "M11526007J", clientName: "SOL LUNA GROUP", contactPerson: "SOL LUNA GROUP", email: "info@sollunagroup.com", phone: "0695555775" },
  { erpId: "1386", nipt: "M53429802O", clientName: "URBAN X", contactPerson: "URBAN X", email: "olti.kaja@outlook.com", phone: "0697808555" },
  { erpId: "1385", nipt: "K21622001M", clientName: "AGI KONS", contactPerson: "AGI KONS", email: "info@agikons.com", phone: "04235536" },
  { erpId: "1384", nipt: "", clientName: "ARJAN PELIUSHI", contactPerson: "ARJAN PELIUSHI", email: "", phone: "" },
  { erpId: "1383", nipt: "", clientName: "Ylvije Cena", contactPerson: "Ylvije Cena", email: "", phone: "" },
  { erpId: "1382", nipt: "", clientName: "Melsi Pashollari", contactPerson: "Melsi Pashollari", email: "", phone: "" },
  { erpId: "1381", nipt: "", clientName: "Gezim Korani", contactPerson: "Gezim Korani", email: "", phone: "" },
  { erpId: "1380", nipt: "M01726016N", clientName: "Delta Cooperation And Investment", contactPerson: "Delta Cooperation And Investment", email: "financadci@gmail.com", phone: "0682064624" },
  { erpId: "1379", nipt: "", clientName: "Franko Lazaj", contactPerson: "Franko Lazaj", email: "", phone: "" },
  { erpId: "1378", nipt: "", clientName: "Durim Hasanpavaj", contactPerson: "Durim Hasanpavaj", email: "", phone: "" },
  { erpId: "1377", nipt: "", clientName: "Agron Beiko", contactPerson: "Agron Beiko", email: "", phone: "" },
  { erpId: "1376", nipt: "", clientName: "Ervis Site", contactPerson: "Ervis Site", email: "", phone: "" },
  { erpId: "1375", nipt: "M41324503R", clientName: "VRETO CONSTRUCTION", contactPerson: "VRETO CONSTRUCTION", email: "", phone: "" },
  { erpId: "1374", nipt: "J66903237U", clientName: "Andi Shpk", contactPerson: "Andi Shpk", email: "marjetaqose@gmail.com", phone: "0692051006" },
  { erpId: "1372", nipt: "", clientName: "Erland", contactPerson: "Erland", email: "", phone: "" },
  { erpId: "1371", nipt: "", clientName: "Gezim Alia", contactPerson: "Gezim Alia", email: "", phone: "" },
  { erpId: "1370", nipt: "", clientName: "Arben Luro", contactPerson: "Arben Luro", email: "", phone: "" },
  { erpId: "1369", nipt: "M21407022B", clientName: "Dukagjini Group", contactPerson: "Dukagjini Group", email: "korab.lluka@dukagjinigroup.com", phone: "355694017888" },
  { erpId: "1368", nipt: "", clientName: "Besnik Fetahu", contactPerson: "Besnik Fetahu", email: "", phone: "" },
  { erpId: "1367", nipt: "L72527001T", clientName: "KUMANI - CONSTRUCION", contactPerson: "KUMANI - CONSTRUCION", email: "kumaniconstrucion@gmail.com", phone: "0692128657" },
  { erpId: "1366", nipt: "", clientName: "Besnik Xhelilaj", contactPerson: "Besnik Xhelilaj", email: "", phone: "" },
  { erpId: "1365", nipt: "J97511807W", clientName: "CAUSHI Shpk", contactPerson: "CAUSHI", email: "caushi.shpk@gmail.com", phone: "0692060288" },
  { erpId: "1364", nipt: "", clientName: "Gentian Luzi", contactPerson: "Gentian Luzi", email: "", phone: "" },
  { erpId: "1363", nipt: "M22220006L", clientName: "Vega Energy", contactPerson: "Vega Energy", email: "skender.hoxhaj@vegagroup.al", phone: "0694021115" },
  { erpId: "1362", nipt: "", clientName: "Njazi Ademi", contactPerson: "Njazi Ademi", email: "", phone: "" },
  { erpId: "1361", nipt: "K51723002I", clientName: "Rimi 1 shpk", contactPerson: "Rimi 1 shpk", email: "nurjaagron@gmail.com", phone: "0676104200" },
  { erpId: "1360", nipt: "L72226017O", clientName: "ROKLI-CONSTRUCSION", contactPerson: "ROKLI-CONSTRUCSION", email: "rokliconstrucsion@gmail.com", phone: "0693227557" },
  { erpId: "1359", nipt: "K72522812K", clientName: "ERGI SHPK", contactPerson: "ERGI SHPK", email: "finance@supreme.com.al", phone: "0674022115" }
];
