import type { Equipment } from "./equipment";

/**
 * The calibrated instruments, taken from SL-FB-6.4.7 PROGRAMI I KALIBRIMIT TË
 * PAJISJEVE LABORATORIKE (Versioni 7, viti 2026), updated 13.05.2026 by the
 * Quality Manager and approved by the Head of Laboratory.
 *
 * Generated from the workbook cells rather than retyped, so the register and
 * the controlled document cannot quietly disagree about a date or a
 * certificate number.
 *
 * These 29 are the instruments under formal calibration. The rest of the
 * ~1,100-row inventory in SL-FB-6.4.1 carries identity only and can be added
 * without changing the shape of the record.
 */
/**
 * uniqueCode is optional here alone: the AEP pressure gauge on the form has no
 * code in that column. Inventing one would put a number in the register that
 * appears nowhere on the instrument or the certificate, so the gap is carried
 * through and shown as a gap.
 */
type SeedRow = Omit<Equipment, "id" | "status" | "createdAt" | "uniqueCode"> & { uniqueCode?: string };

const ROWS: SeedRow[] = [
  {
    uniqueCode: "PT2",
    name: "Presa në shtypje",
    field: "Pajisje matëse të forcës",
    measuringRange: "deri në 2000 kN",
    accuracyClass: "Class 1",
    manufacturer: "CONTROLS, Italy",
    model: "201E1.X0828",
    serialNumber: "7701003",
    calibrationType: "I jashtëm",
    lastCalibration: "03.09.2025",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Gusht 2026",
    nextCalibrationDate: "31.08.2026",
    calibrationBody: "RBC Media",
    certificateCode: "24/0646F"
  },
  {
    uniqueCode: "FM38/1",
    name: "Presa në shtypje",
    field: "Pajisje matëse të forcës",
    measuringRange: "deri në 2000 kN",
    accuracyClass: "Class 1",
    manufacturer: "CONTROLS, Italy",
    model: "50-C46G2",
    serialNumber: "2031447",
    calibrationType: "I jashtëm",
    lastCalibration: "03.09.2025",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Gusht 2026",
    nextCalibrationDate: "31.08.2026",
    calibrationBody: "RBC Media",
    certificateCode: "25/0798F"
  },
  {
    uniqueCode: "FM39",
    name: "Presa në shtypje elektromekanike universale",
    field: "Pajisje matëse të forcës",
    measuringRange: "deri në 50 kN",
    accuracyClass: "Class 1",
    manufacturer: "CONTROLS, Italy",
    model: "70-T0108/E/TCE",
    serialNumber: "03116015/112572",
    calibrationType: "I jashtëm",
    lastCalibration: "03.09.2025",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Gusht 2026",
    nextCalibrationDate: "31.08.2026",
    calibrationBody: "RBC Media",
    certificateCode: "25/0799F"
  },
  {
    uniqueCode: "FM165",
    name: "Presa në shtypje-tërheqje",
    field: "Pajisje matëse të forcës",
    measuringRange: "deri në 500/600 kN",
    accuracyClass: "Class 2 (intervali 100 kN)/Class 1 (intervali 100 kN)/Class 0.5 (intervali 200.5÷500 kN)",
    manufacturer: "UTEST, Turkey",
    model: "UTM-4000",
    serialNumber: "06/013",
    calibrationType: "I jashtëm",
    lastCalibration: "03.09.2025",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Gusht 2026",
    nextCalibrationDate: "31.08.2026",
    calibrationBody: "RBC Media",
    certificateCode: "25/0802F"
  },
  {
    uniqueCode: "LB3",
    name: "Presa në përkulje",
    field: "Pajisje matëse të forcës",
    measuringRange: "deri në 100 kN",
    accuracyClass: "Class 1",
    manufacturer: "CONTROLS, Italy",
    model: "53-C0900",
    serialNumber: "2031654",
    calibrationType: "I jashtëm",
    lastCalibration: "03.09.2025",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Gusht 2026",
    nextCalibrationDate: "31.08.2026",
    calibrationBody: "RBC Media",
    certificateCode: "25/0801F"
  },
  {
    uniqueCode: "FM178",
    name: "Presa Marshall",
    field: "Pajisje matëse të forcës",
    measuringRange: "deri në 50kN",
    accuracyClass: "Class 1",
    manufacturer: "CONTROLS, Italy",
    serialNumber: "2105942",
    calibrationType: "I jashtëm",
    lastCalibration: "03.09.2025",
    calibrationInterval: "2 herë në vit",
    nextCalibrationPeriod: "Gusht 2026",
    nextCalibrationDate: "31.08.2026",
    calibrationBody: "RBC Media",
    certificateCode: "25/0800F"
  },
  {
    uniqueCode: "GJ9",
    name: "Oedometer automatik",
    field: "Pajisje matëse të forcës",
    measuringRange: "15000/10000 N",
    manufacturer: "WYKEHAM -FARRANCE/AEP, Italy",
    model: "TS",
    serialNumber: "1400973/228408",
    calibrationType: "I jashtëm",
    lastCalibration: "03.09.2025",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Gusht 2026",
    nextCalibrationDate: "31.08.2026",
    calibrationBody: "RBC Media",
    certificateCode: "25/0804F"
  },
  {
    uniqueCode: "GJ6",
    name: "Shear apparatus",
    field: "Pajisje matëse të forcës",
    measuringRange: "5000 N",
    accuracyClass: "Class 1",
    manufacturer: "WYKEHAM -FARRANCE/AEP, Italy",
    model: "27-WF25420/TS05",
    serialNumber: "07006219/325357",
    calibrationType: "I jashtëm",
    lastCalibration: "03.09.2025",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Gusht 2026",
    nextCalibrationDate: "31.08.2026",
    calibrationBody: "RBC Media",
    certificateCode: "25/0803F"
  },
  {
    uniqueCode: "K12",
    name: "Peshore elektronike",
    field: "Pajisje matëse të peshës",
    measuringRange: "Max.=210 g, d=0.1 mg",
    accuracyClass: "Class I",
    manufacturer: "OHAUS",
    model: "PA214C",
    serialNumber: "8729512353",
    calibrationType: "I jashtëm",
    lastCalibration: "13.05.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Maj 2027",
    nextCalibrationDate: "12.05.2027",
    calibrationBody: "Drejtoria e Përgjithshme e Metrologjisë",
    certificateCode: "LM-0526P213"
  },
  {
    uniqueCode: "FM10",
    name: "Peshore elektronike",
    field: "Pajisje matëse të peshës",
    measuringRange: "Max.=4200 g, d=0.01 g",
    accuracyClass: "Class II",
    manufacturer: "KERN",
    model: "EG 4200-2NM",
    serialNumber: "74950293",
    calibrationType: "I jashtëm",
    lastCalibration: "13.05.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Maj 2027",
    nextCalibrationDate: "12.05.2027",
    calibrationBody: "Drejtoria e Përgjithshme e Metrologjisë",
    certificateCode: "LM-0526P214"
  },
  {
    uniqueCode: "FM185",
    name: "Peshore elektronike",
    field: "Pajisje matëse të peshës",
    measuringRange: "Max.=30 kg, d=0.1 g",
    accuracyClass: "Class II",
    manufacturer: "NECKLIFE",
    model: "JZC-TSC-30",
    calibrationType: "I jashtëm",
    lastCalibration: "13.05.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Maj 2027",
    nextCalibrationDate: "12.05.2027",
    calibrationBody: "Drejtoria e Përgjithshme e Metrologjisë",
    certificateCode: "LM-0526P215"
  },
  {
    uniqueCode: "FM24",
    name: "Peshore elektronike",
    field: "Pajisje matëse të peshës",
    measuringRange: "Max.=40 kg, d=2 g",
    accuracyClass: "Class III",
    manufacturer: "CONSTANT",
    model: "14192-44",
    serialNumber: "14192",
    calibrationType: "I jashtëm",
    lastCalibration: "13.05.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Maj 2027",
    nextCalibrationDate: "12.05.2027",
    calibrationBody: "Drejtoria e Përgjithshme e Metrologjisë",
    certificateCode: "LM-0526P217"
  },
  {
    uniqueCode: "FM166/2",
    name: "Peshore elektronike",
    field: "Pajisje matëse të peshës",
    measuringRange: "Max.=8100 g, d=0.1 g",
    accuracyClass: "Class II",
    manufacturer: "METTLER TOLEDO",
    model: "SB 8001",
    serialNumber: "1121510620",
    calibrationType: "I jashtëm",
    lastCalibration: "13.05.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Maj 2027",
    nextCalibrationDate: "12.05.2027",
    calibrationBody: "Drejtoria e Përgjithshme e Metrologjisë",
    certificateCode: "LM-0526P216"
  },
  {
    uniqueCode: "GJ-3/6/3",
    name: "Dial gauge",
    field: "Pajisje matëse të gjatësisë",
    measuringRange: "Intervali i matjes 0÷30 mm; rezolucioni 0.01 mm",
    serialNumber: "636",
    calibrationType: "I jashtëm",
    lastCalibration: "13.02.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Shkurt 2027",
    nextCalibrationDate: "12.02.2027",
    calibrationBody: "Autoinstrument Doo",
    certificateCode: "LM26LAB-0101"
  },
  {
    uniqueCode: "GJ-3/6/4",
    name: "Dial gauge",
    field: "Pajisje matëse të gjatësisë",
    measuringRange: "Intervali i matjes 0÷30 mm; rezolucioni 0.01 mm",
    manufacturer: "IDF",
    serialNumber: "227712",
    calibrationType: "I jashtëm",
    lastCalibration: "13.02.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Shkurt 2027",
    nextCalibrationDate: "12.02.2027",
    calibrationBody: "Autoinstrument Doo",
    certificateCode: "LM26LAB-0098"
  },
  {
    uniqueCode: "GJ-3/6/1",
    name: "Dial gauge",
    field: "Pajisje matëse të gjatësisë",
    measuringRange: "Intervali i matjes 0÷30 mm; rezolucioni 0.01 mm",
    manufacturer: "IDF",
    serialNumber: "218591",
    calibrationType: "I jashtëm",
    lastCalibration: "13.02.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Shkurt 2027",
    nextCalibrationDate: "12.02.2027",
    calibrationBody: "Autoinstrument Doo",
    certificateCode: "LM26LAB-0097"
  },
  {
    uniqueCode: "GJ-3/6",
    name: "Dial gauge",
    field: "Pajisje matëse të gjatësisë",
    measuringRange: "Intervali i matjes 0÷30 mm; rezolucioni 0.01 mm",
    manufacturer: "IDF",
    serialNumber: "32176",
    calibrationType: "I jashtëm",
    lastCalibration: "13.02.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Shkurt 2027",
    nextCalibrationDate: "12.02.2027",
    calibrationBody: "Autoinstrument Doo",
    certificateCode: "LM26LAB-0099"
  },
  {
    uniqueCode: "FM14",
    name: "Kaliber Vernier",
    field: "Pajisje matëse të gjatësisë",
    measuringRange: "Intervali i matjes 0÷300 mm; rezolucioni 0.02 mm",
    manufacturer: "UIK",
    serialNumber: "5-96",
    calibrationType: "I jashtëm",
    lastCalibration: "13.02.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Shkurt 2027",
    nextCalibrationDate: "12.02.2027",
    calibrationBody: "Autoinstrument Doo",
    certificateCode: "LM25LAB-0045"
  },
  {
    uniqueCode: "FM15",
    name: "Kaliber Vernier",
    field: "Pajisje matëse të gjatësisë",
    measuringRange: "Intervali i matjes 0÷200 mm; rezolucioni 0.05 mm",
    manufacturer: "CONTROLS, Italy",
    model: "47-D0542/A",
    serialNumber: "14004020",
    calibrationType: "I jashtëm",
    lastCalibration: "13.02.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Shkurt 2027",
    nextCalibrationDate: "12.02.2027",
    calibrationBody: "Autoinstrument Doo",
    certificateCode: "LM26LAB-0095"
  },
  {
    uniqueCode: "LB24",
    name: "Vizore metalike",
    field: "Pajisje matëse të gjatësisë",
    measuringRange: "Intervali i matjes 0÷500 mm; rezolucioni 1 mm",
    serialNumber: "A1309",
    calibrationType: "I jashtëm",
    lastCalibration: "13.02.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Shkurt 2027",
    nextCalibrationDate: "12.02.2027",
    calibrationBody: "Autoinstrument Doo",
    certificateCode: "LM26LAB-0100"
  },
  {
    uniqueCode: "K6",
    name: "Termoçift dixhital me sondë",
    field: "Pajisje matëse të temperaturës",
    measuringRange: "Intervali i matjes -50÷200 oC; rezolucioni 0.1 oC",
    accuracyClass: "Type K",
    manufacturer: "HANNA INSTRUMENTS",
    model: "HI 935005N",
    serialNumber: "A2295/08495958",
    calibrationType: "I jashtëm",
    lastCalibration: "13.02.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Shkurt 2027",
    nextCalibrationDate: "12.02.2027",
    calibrationBody: "Autoinstrument Doo",
    certificateCode: "TP26LAB-0027"
  },
  {
    uniqueCode: "K22",
    name: "Termometer prej qelqi (me zhytje të pjesshme)",
    field: "Pajisje matëse të temperaturës",
    measuringRange: "Intervali i matjes 57÷65 oC; rezolucioni 0.1 oC",
    manufacturer: "ASTM",
    model: "Type 20C",
    serialNumber: "AA2607",
    calibrationType: "I jashtëm",
    lastCalibration: "13.02.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Shkurt 2027",
    nextCalibrationDate: "12.02.2027",
    calibrationBody: "Autoinstrument Doo",
    certificateCode: "TP26LAB-0026"
  },
  {
    uniqueCode: "K17",
    name: "Kohëmatës dixhital",
    field: "Pajisje matëse të kohës",
    measuringRange: "Intervali i matjes 00:00:00÷00:30:00 h:min:s; rezolucioni 0.01 s; Intervali i matjes 00:30:00÷12:00:00 h:min:s; rezolucioni 1 s",
    model: "ZSD-009",
    serialNumber: "A2605",
    calibrationType: "I jashtëm",
    lastCalibration: "13.02.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Shkurt 2027",
    nextCalibrationDate: "12.02.2027",
    calibrationBody: "Autoinstrument Doo",
    certificateCode: "SW26LAB-0027"
  },
  {
    uniqueCode: "GJ-DC-1",
    name: "Manometer presioni",
    field: "Pajisje matëse të presionit",
    measuringRange: "Intervali i matjes 0÷50 kN (344.80 bar), rezolucioni 0.25 kN (1.72 bar)",
    manufacturer: "CONTROLS, Italy",
    model: "Hydraulic",
    serialNumber: "5A00010",
    calibrationType: "I jashtëm",
    lastCalibration: "29.08.2024",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Gusht 2025",
    nextCalibrationDate: "29.08.2025",
    calibrationBody: "Drejtoria e Përgjithshme e Metrologjisë",
    certificateCode: "LP-0824M013"
  },
  {
    name: "Manometer presioni",
    field: "Pajisje matëse të presionit",
    measuringRange: "Intervali i matjes 0÷700 bar, rezolucioni 0.01 bar",
    manufacturer: "AEP Transducers",
    model: "Hydraulic dixhital",
    serialNumber: "935293",
    calibrationType: "I jashtëm",
    lastCalibration: "24.09.2025",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Shtator 2026",
    nextCalibrationDate: "23.09.2026",
    calibrationBody: "Drejtoria e Përgjithshme e Metrologjisë",
    certificateCode: "LP-0925M031"
  },
  {
    uniqueCode: "FM32/3",
    name: "Manometer presioni",
    field: "Pajisje matëse të presionit",
    measuringRange: "Intervali i matjes 0÷10 bar, rezolucioni 0.5 bar",
    accuracyClass: "Class 1.6",
    manufacturer: "R",
    model: "Manual",
    serialNumber: "008",
    calibrationType: "I jashtëm",
    lastCalibration: "24.09.2025",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Shtator 2026",
    nextCalibrationDate: "23.09.2026",
    calibrationBody: "Drejtoria e Përgjithshme e Metrologjisë",
    certificateCode: "LP-0925M030"
  },
  {
    uniqueCode: "FM181",
    name: "Termometër",
    field: "Pajisje matëse të temperaturës",
    measuringRange: "Temperatura -50 oC - 300 oC",
    manufacturer: "JY - 300",
    serialNumber: "TP101",
    calibrationType: "I brendshëm",
    lastCalibration: "05.02.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Shkurt 2027",
    nextCalibrationDate: "03.02.2027",
    calibrationBody: "Sarp&Lab Shpk",
    certificateCode: "SL-ÇK-01"
  },
  {
    uniqueCode: "SR01",
    name: "Vizore metalike",
    field: "Pajisje matëse të gjatësisë",
    measuringRange: "Matje dimensionesh nga 0 deri në 300 mm",
    calibrationType: "I brendshëm",
    lastCalibration: "03.02.2026",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Shkurt 2027",
    nextCalibrationDate: "03.02.2027",
    calibrationBody: "Sarp&Lab Shpk",
    certificateCode: "SL-ÇK-01"
  },
  {
    uniqueCode: "LB 23",
    name: "Kaliber",
    field: "Pajisje matëse të gjatësisë",
    measuringRange: "Matje dimensionesh nga 0 deri në 150 mm",
    manufacturer: "VERNIER",
    serialNumber: "1-7659",
    calibrationType: "I brendshëm",
    lastCalibration: "15.10.2025",
    calibrationInterval: "1 herë në vit",
    nextCalibrationPeriod: "Tetor 2026",
    nextCalibrationDate: "14.10.2026",
    calibrationBody: "Sarp&Lab Shpk",
    certificateCode: "SL-ÇK-01"
  }
];

/**
 * Ids are derived from the unique code rather than random, so re-seeding an
 * environment produces the same records and a code can be found by its id.
 * The one instrument on the form without a code — the AEP pressure gauge — is
 * keyed by its serial instead, so it still has a stable identity.
 */
export const equipmentSeed: Equipment[] = ROWS.map((row) => ({
  ...row,
  uniqueCode: row.uniqueCode ?? "",
  id:
    "eq-" +
    (row.uniqueCode || row.serialNumber || row.name)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, ""),
  status: "Në përdorim" as const,
  createdAt: "2026-09-19T00:00:00.000Z"
}));
